"""python -m shruti prove <program.s> [--contract file] [--min-P]
python -m shruti train [--captures N] [--seed S] [--out ear/weights/default] [--report file]

prove: proves an Event Machine program against its contract (by default the .contract.yaml
beside it). Exit status 0 on a proof, 1 on a counterexample, 2 on a usage or input error.
train: trains the Ear on simulated buses, writes the weight chain (.hex) and configuration
(.json), and a report with the integer model's accuracy, confusion matrix and OOD rates.
"""

import argparse
import sys
from pathlib import Path


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="shruti")
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("prove", help="prove a program against its contract")
    p.add_argument("program")
    p.add_argument("--contract", help="contract file (default: <program>.contract.yaml)")
    p.add_argument("--min-P", action="store_true",
                   help="also report the smallest P for which the contract holds")
    t = sub.add_parser("train", help="train the Ear classifier on simulated buses")
    t.add_argument("--captures", type=int, default=150, help="captures per class")
    t.add_argument("--seed", type=int, default=1)
    t.add_argument("--out", default="ear/weights/default", help="output stem (.hex, .json)")
    t.add_argument("--report", default="ear/REPORT.md")
    t.add_argument("--no-ood", action="store_true",
                   help="skip the held-out-class (OOD) experiment")
    a = ap.parse_args(argv)
    if a.cmd == "train":
        return _train(a)

    from asm import AsmError, assemble
    from prove import ContractError, contract_for, load_contract, min_P, prove, Unsupported

    try:
        cpath = Path(a.contract) if a.contract else contract_for(a.program)
        import yaml
        kind = (yaml.safe_load(cpath.read_text()) or {}).get("kind")
        if kind in ("receiver", "spi_master", "i2c_master"):
            if kind == "receiver":
                from prove.reactive import load_receiver as load_k, prove_receiver as prove_k
            elif kind == "spi_master":
                from prove.spi import load_spi as load_k, prove_spi as prove_k
            else:
                from prove.i2c import load_i2c, prove_i2c
                out = prove_i2c(load_i2c(cpath), Path(a.program).read_text())
                print(f"{a.program} against {cpath}:")
                print(out.report())
                return 0 if out.proved else 1
            out = prove_k(load_k(cpath), assemble(Path(a.program).read_text(), a.program))
            print(f"{a.program} against {cpath}:")
            print(out.report())
            return 0 if out.proved else 1
        c = load_contract(cpath)
        words = assemble(Path(a.program).read_text(), a.program)
        out = prove(c, words)
    except (AsmError, ContractError, Unsupported, FileNotFoundError) as e:
        print(f"shruti prove: {e}", file=sys.stderr)
        return 2
    print(f"{a.program} against {cpath}:")
    print(out.report())
    if out.proved and c.induction:
        from prove.check import prove_unbounded
        ind = prove_unbounded(c, Path(a.program).read_text())
        print(ind.report())
        if not ind.proved:
            return 1
    if a.min_P and out.proved:
        print(f"smallest P for which the contract holds: {min_P(c, words)}")
    return 0 if out.proved else 1


def _train(a) -> int:
    from ear import protosim as ps
    from ear.train import report_markdown, save, train
    model, report = train(captures_per_class=a.captures, seed=a.seed)
    save(model, report, Path(a.out))
    parts = [report_markdown(report, "All eight classes")]
    if not a.no_ood:
        unknown = ["JTAG/SWD", "PS/2"]
        known = [c for c in ps.CLASSES if c not in unknown]
        _, r2 = train(captures_per_class=a.captures, seed=a.seed, classes=known,
                      unknown=unknown)
        parts.append(report_markdown(r2, "Out-of-distribution check: trained without "
                                         "JTAG/SWD and PS/2"))
    head = (f"# Ear training report\n\nGenerated by `python -m shruti train --captures "
            f"{a.captures} --seed {a.seed}` on simulated buses (ear/protosim.py). Every "
            "number is for the exact integer model (ear/mlp.py) that the hardware runs, on "
            "captures held out of training. Simulated data only: FPGA captures of real "
            "devices come later.\n\n")
    Path(a.report).write_text(head + "\n".join(parts))
    print(Path(a.report).read_text())
    return 0


if __name__ == "__main__":
    sys.exit(main())
