"""What the Ear does beyond its test-set accuracy: coverage across each protocol's speed range,
traffic it was never trained on, held-out classes, an out-of-distribution test it could
have, and how much accuracy the ternary integer model gives up against a float network.

Everything is seeded and deterministic, and every number comes from the exact integer
model in ear.mlp with the shipped weights (ear/weights/default.*) unless a section says
otherwise. `python -m ear.evaluate --write` regenerates the second half of ear/REPORT.md;
`--quick` runs a small version for a smoke test. numpy only.

Definitions used throughout:
- a window is every window the hardware closes, including those the activity gate flags
  (fewer than MIN_EDGES edges); ear.dataset drops those before training, this does not;
- answered: not flagged out-of-distribution (neither the gate nor the logit floor fired),
  so the chip shows a class without its OOD flag;
- confident: answered and confident, which is what the class pins show when the host
  reads them as "answers only when confident";
- precision: the share of confident windows whose class is right.
"""

from __future__ import annotations

import argparse
import math
import random
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Dict, List, Optional, Sequence, Tuple

import numpy as np

from . import protosim as ps
from .dataset import MIN_EDGES, Dataset, build, capture_windows
from .features import extract
from .inpath import BYPASS, filter_pins
from .mlp import CLASSES_N, Model
from .train import TrainConfig, int_logits, load, predict, split, train

HERE = Path(__file__).resolve().parent
WEIGHTS = HERE / "weights" / "default"
REPORT = HERE / "REPORT.md"
MARKER = "<!-- Generated by ear/evaluate.py from here down; edit the code, not the text. -->"
CLK = ps.CLOCK_HZ

# Speed points per class, as the generator's speed argument (cycles at 50 MHz) with a label.
SPEEDS: Dict[str, List[Tuple[str, dict]]] = {
    "UART": [(f"{b:,} baud", {"period": CLK / b, "duplex": False})
             for b in (2400, 9600, 19200, 38400, 57600, 115200, 460800, 1_000_000, 3_000_000)],
    "SPI": [(f"{f} SCK", {"half": h}) for f, h in
            (("100 kHz", 250), ("400 kHz", 62.5), ("1 MHz", 25), ("4 MHz", 6.25), ("12.5 MHz", 2))],
    "I2C": [(f"{f} SCL", {"half": h}) for f, h in
            (("100 kHz", 250), ("400 kHz", 62.5), ("1 MHz", 25))],
    "USB-LS": [("1.5 Mbit/s", {})],
    "CAN": [(f"{f}", {"period": p}) for f, p in
            (("125 kbit/s", 400), ("250 kbit/s", 200), ("500 kbit/s", 100), ("1 Mbit/s", 50))],
    "JTAG/SWD": [(f"{f} TCK", {"half": h}) for f, h in
                 (("100 kHz", 250), ("1 MHz", 25), ("8.3 MHz", 3))],
    "PS/2": [(f"{f} CLK", {"half": h}) for f, h in (("10 kHz", 2500), ("16.7 kHz", 1500))],
    "Manchester": [(f"{f}", {"period": p}) for f, p in
                   (("25 kbit/s", 2000), ("100 kbit/s", 500), ("1 Mbit/s", 50),
                    ("6.25 Mbit/s", 8))],
}
DURATION = 1_500_000                       # 30 ms per capture, as dataset.build gives UART


def shipped() -> Model:
    return load(WEIGHTS)


def hidden_int(model: Model, X: np.ndarray) -> np.ndarray:
    """The 8 hidden units of the integer model (ear.mlp), vectorised."""
    acc = X @ np.array(model.w1).T + np.array(model.bias)
    return np.minimum(255, np.maximum(acc, 0) >> model.cfg.shift)


@dataclass
class Scored:
    windows: int
    answered: float
    accuracy: float          # on answered windows
    confident: float
    precision: float         # on confident windows
    calls: Counter           # predicted class of answered windows
    calls_all: Counter       # predicted class of every window


def score(model: Model, feats: np.ndarray, edges: np.ndarray, truth: Optional[int]) -> Scored:
    n = len(edges)
    if n == 0:
        return Scored(0, 0.0, float("nan"), 0.0, float("nan"), Counter(), Counter())
    lg = int_logits(np.array(model.w1), np.array(model.w2), feats, model.cfg.shift,
                    np.array(model.bias))
    srt = np.sort(lg, axis=1)
    pred = predict(lg)
    ood = (srt[:, -1] < model.cfg.floor) | (edges < model.cfg.min_edges)
    conf = ((srt[:, -1] - srt[:, -2]) >= model.cfg.margin) & ~ood
    ans = ~ood
    right = pred == truth if truth is not None else np.zeros(n, bool)
    return Scored(n, float(ans.mean()),
                  float(right[ans].mean()) if ans.any() else float("nan"),
                  float(conf.mean()),
                  float(right[conf].mean()) if conf.any() else float("nan"),
                  Counter(ps.CLASSES[k] for k in pred[ans]),
                  Counter(ps.CLASSES[k] for k in pred))


# -- coverage by speed (E1, E2) ------------------------------------------------------------

def coverage(model: Model, captures: int = 20, seed: int = 11,
             speeds: Dict[str, List[Tuple[str, dict]]] = SPEEDS, max_windows: int = 40
             ) -> List[Tuple[str, str, float, Scored]]:
    """Every class across its speed range. Gated windows are counted, not dropped."""
    rows = []
    for label, points in speeds.items():
        k = ps.CLASSES.index(label)
        for name, kw in points:
            rng = random.Random(f"{seed}/{label}/{name}")
            feats, edges = [], []
            for _ in range(captures):
                cap = ps.generate(label, rng, duration=DURATION, **kw)
                ws, _ = capture_windows(cap, rng, min_edges=0, max_windows=max_windows)
                feats += [w.features for w in ws]
                edges += [w.edges for w in ws]
            e = np.array(edges, dtype=np.int64)
            s = score(model, np.array(feats, dtype=np.int64).reshape(-1, 72), e, k)
            rows.append((label, name, float(e.mean()) if len(e) else 0.0, s))
    return rows


# -- foreign signals (E3) ------------------------------------------------------------------

def _toggles(times: Sequence[int], pin: int) -> List[Tuple[int, int, int]]:
    out, lvl = [], 0
    for t in times:
        lvl ^= 1
        out.append((t, pin, lvl))
    return out


def pwm(freq: float, duty: float, duration: int = DURATION) -> List[Tuple[int, int, int]]:
    per, ev, t = CLK / freq, [], 0.0
    while t + per < duration:
        ev += [(int(round(t)), 0, 1), (int(round(t + per * duty)), 0, 0)]
        t += per
    return ev


def ws2812(rng: random.Random, duration: int = DURATION) -> List[Tuple[int, int, int]]:
    """WS2812 LED data: 800 kHz bits (0: 0.4 us high, 1: 0.8 us high), 24 bits per LED,
    8 to 60 LEDs per frame, then a reset gap of at least 52 us."""
    ev, t = [], 1000.0
    while True:
        for _ in range(rng.randint(8, 60) * 24):
            if t + 62.5 >= duration:
                return ev
            hi = 40 if rng.random() < 0.5 else 20
            ev += [(int(round(t)), 0, 1), (int(round(t + hi)), 0, 0)]
            t += 62.5
        t += rng.uniform(2600, 30_000)


def random_edges(rng: random.Random, mean: float, pins: int,
                 duration: int = DURATION) -> List[Tuple[int, int, int]]:
    ev = []
    for p in range(pins):
        t, ts = 0.0, []
        while True:
            t += rng.expovariate(1 / mean)
            if t >= duration:
                break
            ts.append(int(t))
        ev += _toggles(sorted(set(ts)), p)
    return sorted(ev)


def clock(freq: float, duration: int = DURATION) -> List[Tuple[int, int, int]]:
    half = CLK / freq / 2
    return _toggles([int(round(k * half)) for k in range(1, int(duration / half))], 0)


def probe_signals(seed: int = 7, duration: int = DURATION
                  ) -> List[Tuple[str, List[Tuple[int, int, int]]]]:
    rng = random.Random(seed)
    return [
        ("PWM, 20 kHz, 20% duty", pwm(20e3, 0.2, duration)),
        ("WS2812 LED data, 800 kHz", ws2812(rng, duration)),
        ("Random edges on 4 pins, mean 1 us", random_edges(rng, 50, 4, duration)),
        ("Random edges on 4 pins, mean 20 us", random_edges(rng, 1000, 4, duration)),
        ("Clock, 1 MHz", clock(1e6, duration)),
        ("Random edges on 1 pin, mean 1 us", random_edges(rng, 50, 1, duration)),
    ]


def probes(model: Model, seed: int = 7, duration: int = DURATION
           ) -> List[Tuple[str, int, Scored]]:
    """Each signal on the Ear's pins with the filter in bypass, once with the unused pins
    idle low and once idle high (training draws both)."""
    rows = []
    for name, edges in probe_signals(seed, duration):
        active = {p for _, p, _ in edges}            # the signals start low
        for idle in (0, 1):
            init = [0 if p in active else idle for p in range(4)]
            ws = extract(init, filter_pins(init, edges, BYPASS), duration)
            s = score(model, np.array([w.features for w in ws], dtype=np.int64).reshape(-1, 72),
                      np.array([w.edges for w in ws], dtype=np.int64), None)
            rows.append((name, idle, s))
    return rows


# -- held-out classes and a prototype-distance OOD test (E4, E5) ----------------------------

KNOWN6 = ["UART", "SPI", "I2C", "USB-LS", "CAN", "Manchester"]
UNKNOWN2 = ["JTAG/SWD", "PS/2"]


@dataclass
class HeldOut:
    report: object
    per_class: Dict[str, Tuple[int, float, float, Counter]]   # windows, floor flag, confident, calls
    prototype: List[Tuple[int, float, Dict[str, float]]]       # percentile, false alarms, flagged


def held_out(captures: int = 150, seed: int = 1, unknown_captures: int = 50,
             tc: TrainConfig = TrainConfig()) -> HeldOut:
    ds = build(captures, seed, KNOWN6)
    model, report = train(captures, seed, KNOWN6, tc, unknown=UNKNOWN2, ds=ds)
    (Xtr, _, _), (Xva, _, _), (Xte, yte, ete) = split(ds, seed)
    du = build(unknown_captures, seed + 1000, UNKNOWN2)
    Xu, yu = np.array(du.X, dtype=np.int64), np.array(du.y)
    lu = int_logits(np.array(model.w1), np.array(model.w2), Xu, model.cfg.shift,
                    np.array(model.bias))
    srt = np.sort(lu, axis=1)
    pu = predict(lu)
    conf = (srt[:, -1] - srt[:, -2]) >= model.cfg.margin
    floor = srt[:, -1] < model.cfg.floor
    per = {}
    for c in UNKNOWN2:
        m = yu == ps.CLASSES.index(c)
        per[c] = (int(m.sum()), float(floor[m].mean()), float(conf[m].mean()),
                  Counter(ps.CLASSES[k] for k in pu[m & conf]))
    # prototype distance: L1 from the hidden vector to its predicted class's mean training
    # hidden vector; the threshold is a percentile of the validation distances
    def dist(X):
        h = hidden_int(model, X)
        p = predict(int_logits(np.array(model.w1), np.array(model.w2), X, model.cfg.shift,
                               np.array(model.bias)))
        return np.abs(h - proto[p]).sum(axis=1)
    htr = hidden_int(model, Xtr)
    ptr = predict(htr @ np.array(model.w2).T)
    proto = np.zeros((CLASSES_N, htr.shape[1]))
    for k in range(CLASSES_N):
        if (ptr == k).any():
            proto[k] = htr[ptr == k].mean(axis=0)
    dva, dte, du_ = dist(Xva), dist(Xte), dist(Xu)
    rows = []
    for pct in (95, 90):
        thr = np.percentile(dva, pct)
        rows.append((pct, float((dte > thr).mean()),
                     {c: float((du_[yu == ps.CLASSES.index(c)] > thr).mean()) for c in UNKNOWN2}))
    return HeldOut(report, per, rows)


# -- float network against the integer model (E6) -------------------------------------------

def float_mlp(Xtr: np.ndarray, ytr: np.ndarray, Xva: np.ndarray, yva: np.ndarray,
              hidden: int, seed: int = 0, epochs: int = 3000, lr: float = 0.01,
              wd: float = 1e-4) -> Callable[[np.ndarray], np.ndarray]:
    """A float MLP (ReLU, biases on both layers, standardised inputs, class-weighted
    cross-entropy, full-batch Adam). Keeps the weights with the best validation accuracy,
    checked every 50 epochs. Returns a predict function."""
    rng = np.random.default_rng(seed)
    mu, sd = Xtr.mean(0), Xtr.std(0) + 1e-6
    x, xv = (Xtr - mu) / sd, (Xva - mu) / sd
    P = [rng.normal(0, math.sqrt(2 / x.shape[1]), (x.shape[1], hidden)), np.zeros(hidden),
         rng.normal(0, math.sqrt(2 / hidden), (hidden, CLASSES_N)), np.zeros(CLASSES_N)]
    counts = np.bincount(ytr, minlength=CLASSES_N).astype(float)
    cw = np.where(counts > 0, counts.sum() / np.maximum(counts, 1) / (counts > 0).sum(), 0.0)
    sw = cw[ytr] / len(ytr)
    onehot = np.eye(CLASSES_N)[ytr]
    M = [np.zeros_like(p) for p in P]
    V = [np.zeros_like(p) for p in P]
    best = (-1.0, [p.copy() for p in P])

    def fwd(params, xx):
        a = xx @ params[0] + params[1]
        h = np.maximum(a, 0)
        return a, h, h @ params[2] + params[3]

    for t in range(1, epochs + 1):
        a, h, z = fwd(P, x)
        z = z - z.max(axis=1, keepdims=True)
        p = np.exp(z)
        p /= p.sum(axis=1, keepdims=True)
        gz = (p - onehot) * sw[:, None]
        ga = (gz @ P[2].T) * (a > 0)
        G = [x.T @ ga + wd * P[0], ga.sum(0), h.T @ gz + wd * P[2], gz.sum(0)]
        for i in range(4):
            M[i] = 0.9 * M[i] + 0.1 * G[i]
            V[i] = 0.999 * V[i] + 0.001 * G[i] ** 2
            P[i] -= lr * (M[i] / (1 - 0.9 ** t)) / (np.sqrt(V[i] / (1 - 0.999 ** t)) + 1e-8)
        if t % 50 == 0:
            acc = float((np.argmax(fwd(P, xv)[2], axis=1) == yva).mean())
            if acc > best[0]:
                best = (acc, [q.copy() for q in P])
    W = best[1]
    return lambda X: np.argmax(fwd(W, (X - mu) / sd)[2], axis=1)


def float_gap(model: Model, captures: int = 150, seed: int = 1,
              sizes: Sequence[int] = (8, 12, 16, 32), epochs: int = 3000
              ) -> List[Tuple[str, float, float]]:
    """Accuracy and UART recall on the shipped model's own test split (build(150, 1), split
    by capture 70/15/15), for float networks trained on its training split."""
    ds = build(captures, seed)
    (Xtr, ytr, _), (Xva, yva, _), (Xte, yte, _) = split(ds, seed)
    uart = yte == ps.CLASSES.index("UART")
    pi = predict(int_logits(np.array(model.w1), np.array(model.w2), Xte, model.cfg.shift,
                            np.array(model.bias)))
    rows = [("Shipped integer model (ternary, 8 hidden)", float((pi == yte).mean()),
             float((pi[uart] == yte[uart]).mean()))]
    for n in sizes:
        f = float_mlp(Xtr.astype(float), ytr, Xva.astype(float), yva, n, seed=0, epochs=epochs)
        pf = f(Xte.astype(float))
        rows.append((f"Float MLP, {n} hidden", float((pf == yte).mean()),
                     float((pf[uart] == yte[uart]).mean())))
    return rows


# -- report ----------------------------------------------------------------------------------

def _pct(v: float) -> str:
    return "-" if v != v else f"{100 * v:.0f}%"


def markdown(cov, prb, ho: Optional[HeldOut], gap, duration: int = DURATION,
             captures: int = 20, gap_captures: int = 150) -> str:
    L = [MARKER, "", "## Coverage by speed",
         "",
         f"Every class at fixed speeds across the range the protocol simulator covers, "
         f"{captures} captures of {DURATION:,} cycles (30 ms) per speed, with the shipped "
         "weights (up to 40 windows per capture). Windows the "
         "activity gate flags (fewer than MIN_EDGES edges) are counted here; the training "
         "report above drops them. Answered: not flagged out-of-distribution. Confident: "
         "answered and confident, which is what \"answers only when confident\" shows. "
         "Precision: right among the confident windows.", "",
         "| Class | Speed | Windows | Mean edges | Answered | Accuracy (answered) | Confident "
         "| Precision | Most common answer |",
         "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    for label, name, me, s in cov:
        top = ", ".join(f"{c} {_pct(n / max(1, sum(s.calls.values())))}"
                        for c, n in s.calls.most_common(2)) or "-"
        L.append(f"| {label} | {name} | {s.windows} | {me:.1f} | {_pct(s.answered)} | "
                 f"{_pct(s.accuracy)} | {_pct(s.confident)} | {_pct(s.precision)} | {top} |")
    L += ["", "A 65,536-cycle window lasts 1.3 ms, so a slow bus closes most windows by time "
          "with only a handful of edges, and the activity gate (MIN_EDGES 24) flags them.", "",
          "## Signals the Ear was never trained on", "",
          "Each signal on one Ear pin (four pins for the random edges), filter in bypass, "
          f"{duration:,} cycles, shipped weights. Training draws the idle level of unused "
          "pins at random, so both levels are shown.", "",
          "| Signal | Unused pins idle | Windows | OOD flag | Confident | Most common class |",
          "| --- | --- | --- | --- | --- | --- |"]
    for name, idle, s in prb:
        top = ", ".join(f"{c} {n}" for c, n in s.calls_all.most_common(2)) or "-"
        L.append(f"| {name} | {'high' if idle else 'low'} | {s.windows} | "
                 f"{_pct(1 - s.answered)} | {_pct(s.confident)} | {top} |")
    if ho is not None:
        r = ho.report
        L += ["", "## Classes held out of training", "",
              f"The model trained on {', '.join(KNOWN6)} only (the second section above: "
              f"{r.test_accuracy:.1%} test accuracy, MARGIN {r.margin}, FLOOR {r.floor}), "
              f"run on held-out JTAG/SWD and PS/2 windows (build(50, 1001)).", "",
              "| Held-out class | Windows | Floor flag | Confident | Confident calls |",
              "| --- | --- | --- | --- | --- |"]
        for c, (n, fl, cf, calls) in ho.per_class.items():
            L.append(f"| {c} | {n} | {_pct(fl)} | {_pct(cf)} | "
                     f"{', '.join(f'{k} {v}' for k, v in calls.most_common()) or '-'} |")
        L += ["", "Prototype distance, the out-of-distribution test the risk table proposed: the "
              "L1 distance from a window's hidden vector to the mean hidden vector of its "
              "predicted class on the training windows, flagged above a percentile of the "
              "validation distances.", "",
              "| Threshold | False alarms (known classes, test) | JTAG/SWD flagged | PS/2 flagged |",
              "| --- | --- | --- | --- |"]
        for pct, fa, fl in ho.prototype:
            L.append(f"| {pct}th percentile | {_pct(fa)} | {_pct(fl['JTAG/SWD'])} | "
                     f"{_pct(fl['PS/2'])} |")
    L += ["", "## Float network against the integer model", "",
          f"The same features and the shipped model's own split (build({gap_captures}, 1), "
          "by capture, 70/15/15; the float networks train on its 70%, pick their epoch on the "
          "15% validation set and are scored on the 15% test set). The "
          "float networks are trained here with numpy; the gap is what ternary weights and "
          "integer requantisation cost.", "",
          "| Model | Test accuracy | UART recall |", "| --- | --- | --- |"]
    for name, acc, ur in gap:                      # rounded as the training report rounds
        L.append(f"| {name} | {round(acc, 4):.1%} | {ur:.0%} |")
    return "\n".join(L) + "\n"


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Evaluate the Ear beyond its test set.")
    ap.add_argument("--quick", action="store_true", help="small run for a smoke test")
    ap.add_argument("--write", action="store_true", help="regenerate the end of ear/REPORT.md")
    a = ap.parse_args(argv)
    model = shipped()
    if a.quick:
        cov = coverage(model, captures=2, speeds={"UART": SPEEDS["UART"][:2]})
        prb = probes(model, duration=200_000)
        ho = None
        gap = float_gap(model, captures=10, sizes=(8,), epochs=200)
    else:
        cov = coverage(model)
        prb = probes(model)
        ho = held_out()
        gap = float_gap(model)
    md = markdown(cov, prb, ho, gap, **({"duration": 200_000, "captures": 2,
                                         "gap_captures": 10} if a.quick else {}))
    if a.write:
        text = REPORT.read_text()
        head = text.split(MARKER)[0].rstrip() + "\n\n"
        REPORT.write_text(head + md)
    print(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
